### ISSUE TITLE
Changing Enum Values Causes Errors

### ISSUE THREAD

**Issue by jrDev1** [LifeandStyleMedia/UAlive#70]
Hello,

When I changed the values of an Enum Class it throws an constant error and won't show inspector of the class anymore:

<img width="870" alt="image" src="https://user-images.githubusercontent.com/16272193/94053441-56c05600-fda8-11ea-8db3-71da0e21e6c6.png">
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/16272193/94053464-5f189100-fda8-11ea-8623-3a29b91b4c6c.png">

Thanks,
jrDev

**Comment by JasonJonesLASM** [comment]
Added a null check to the property drawer, but I cannot reproduce this. I made a new Enum. compiled it. Set a new variable in the Class asset of that Enum type. Set its Enum value in the inspector because its on a MonoBehaviour. Changed the name of that value, and the index. The Enum becomes unselected and blank if the index no longer exists, but there is no errors. The Button is just blank until you select a new one. I'll be doing a little work in this area because of the other area, so we will see if that fixes this for you. If not I'll reopen if you can reproduce specific steps for me.
