### ISSUE TITLE
Cannot Delete Entry Unit even when pasted from a different graph

### ISSUE THREAD

**Issue by thezoob** [LifeandStyleMedia/UAlive#78]
I am not able to delete the Entry node in an Override Method (probably also custom method) even when I paste an Entry unit from a different graph.

**Comment by JasonJonesLASM** [comment]
Yes you'll never be able to delete it. It's a requirement of a method. Now copying and pasting should definitely not be allowed though. If you delete it there is no longer anywhere for Flow to begin. Thought I covered copying, but apparently not.

**Comment by JasonJonesLASM** [comment]
Fixed. So this was stupidly dumb. We override canCopy in the Widget to false. Just looked in the source. Its an unused property essentially. It does nothing. Reported it not working a year and a half ago, guess nothing was done about it.

I hacked something together. You can see the unit still being pasted, but it will delete itself and log a warning in the console that you shouldn't attempt this. Harmless though.

I ended up having to manually select the unit via code and initiate the Delete process, but only when not in the Repaint phase of editors, which was only allowed in overriding the input methods on widgets. 

I dunno lol it was such a dumb thing I had to do because Bolt is missing an `if(canCopy)` statement in the code where they handle pasting.
